# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratings_features_app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aratings_features_app.proto\x12\x14ratings.features.app\"\x1e\n\x0fGetVotesRequest\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"Q\n\x10GetVotesResponse\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\x12\x16\n\x0etotal_up_votes\x18\x02 \x01(\x04\x12\x18\n\x10total_down_votes\x18\x03 \x01(\x04\x32\x62\n\x03\x41pp\x12[\n\x08GetVotes\x12%.ratings.features.app.GetVotesRequest\x1a&.ratings.features.app.GetVotesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ratings_features_app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETVOTESREQUEST']._serialized_start=52
  _globals['_GETVOTESREQUEST']._serialized_end=82
  _globals['_GETVOTESRESPONSE']._serialized_start=84
  _globals['_GETVOTESRESPONSE']._serialized_end=165
  _globals['_APP']._serialized_start=167
  _globals['_APP']._serialized_end=265
# @@protoc_insertion_point(module_scope)
