# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratings_features_chart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cratings_features_chart.proto\x12\x16ratings.features.chart\"x\n\x0fGetChartRequest\x12\x34\n\ttimeframe\x18\x01 \x01(\x0e\x32!.ratings.features.chart.Timeframe\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.ratings.features.chart.ChartType\"\xb8\x01\n\x10GetChartResponse\x12\x34\n\ttimeframe\x18\x01 \x01(\x0e\x32!.ratings.features.chart.Timeframe\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.ratings.features.chart.ChartType\x12=\n\x12ordered_chart_data\x18\x03 \x03(\x0b\x32!.ratings.features.chart.ChartData\"J\n\tChartData\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\x12\x16\n\x0etotal_up_votes\x18\x02 \x01(\x04\x12\x18\n\x10total_down_votes\x18\x03 \x01(\x04*?\n\tChartType\x12\x1e\n\x1a\x43HART_TYPE_TOP_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x43HART_TYPE_TOP\x10\x01*O\n\tTimeframe\x12\x19\n\x15TIMEFRAME_UNSPECIFIED\x10\x00\x12\x12\n\x0eTIMEFRAME_WEEK\x10\x01\x12\x13\n\x0fTIMEFRAME_MONTH\x10\x02\x32h\n\x05\x43hart\x12_\n\x08GetChart\x12\'.ratings.features.chart.GetChartRequest\x1a(.ratings.features.chart.GetChartResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ratings_features_chart_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CHARTTYPE']._serialized_start=441
  _globals['_CHARTTYPE']._serialized_end=504
  _globals['_TIMEFRAME']._serialized_start=506
  _globals['_TIMEFRAME']._serialized_end=585
  _globals['_GETCHARTREQUEST']._serialized_start=56
  _globals['_GETCHARTREQUEST']._serialized_end=176
  _globals['_GETCHARTRESPONSE']._serialized_start=179
  _globals['_GETCHARTRESPONSE']._serialized_end=363
  _globals['_CHARTDATA']._serialized_start=365
  _globals['_CHARTDATA']._serialized_end=439
  _globals['_CHART']._serialized_start=587
  _globals['_CHART']._serialized_end=691
# @@protoc_insertion_point(module_scope)
