//! Contains autogenerated protobuf implementations from [`prost`].

#![allow(rustdoc::broken_intra_doc_links)]
#![allow(missing_docs)]
#![allow(clippy::missing_docs_in_private_items)]

pub mod app {
    include!("../../proto/ratings.features.app.rs");
}

pub mod common {
    include!("../../proto/ratings.features.common.rs");
}

pub mod user {
    include!("../../proto/ratings.features.user.rs");
}

pub mod chart {
    include!("../../proto/ratings.features.chart.rs");
}
