# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratings_features_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bratings_features_user.proto\x12\x15ratings.features.user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n\x13\x41uthenticateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x14\x41uthenticateResponse\x12\r\n\x05token\x18\x01 \x01(\t\",\n\x12ListMyVotesRequest\x12\x16\n\x0esnap_id_filter\x18\x01 \x01(\t\"A\n\x13ListMyVotesResponse\x12*\n\x05votes\x18\x01 \x03(\x0b\x32\x1b.ratings.features.user.Vote\"&\n\x13GetSnapVotesRequest\x12\x0f\n\x07snap_id\x18\x01 \x01(\t\"B\n\x14GetSnapVotesResponse\x12*\n\x05votes\x18\x01 \x03(\x0b\x32\x1b.ratings.features.user.Vote\"n\n\x04Vote\x12\x0f\n\x07snap_id\x18\x01 \x01(\t\x12\x15\n\rsnap_revision\x18\x02 \x01(\x05\x12\x0f\n\x07vote_up\x18\x03 \x01(\x08\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"F\n\x0bVoteRequest\x12\x0f\n\x07snap_id\x18\x01 \x01(\t\x12\x15\n\rsnap_revision\x18\x02 \x01(\x05\x12\x0f\n\x07vote_up\x18\x03 \x01(\x08\x32\xc6\x03\n\x04User\x12i\n\x0c\x41uthenticate\x12*.ratings.features.user.AuthenticateRequest\x1a+.ratings.features.user.AuthenticateResponse\"\x00\x12:\n\x06\x44\x65lete\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x04Vote\x12\".ratings.features.user.VoteRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x66\n\x0bListMyVotes\x12).ratings.features.user.ListMyVotesRequest\x1a*.ratings.features.user.ListMyVotesResponse\"\x00\x12i\n\x0cGetSnapVotes\x12*.ratings.features.user.GetSnapVotesRequest\x1a+.ratings.features.user.GetSnapVotesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ratings_features_user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTHENTICATEREQUEST']._serialized_start=116
  _globals['_AUTHENTICATEREQUEST']._serialized_end=149
  _globals['_AUTHENTICATERESPONSE']._serialized_start=151
  _globals['_AUTHENTICATERESPONSE']._serialized_end=188
  _globals['_LISTMYVOTESREQUEST']._serialized_start=190
  _globals['_LISTMYVOTESREQUEST']._serialized_end=234
  _globals['_LISTMYVOTESRESPONSE']._serialized_start=236
  _globals['_LISTMYVOTESRESPONSE']._serialized_end=301
  _globals['_GETSNAPVOTESREQUEST']._serialized_start=303
  _globals['_GETSNAPVOTESREQUEST']._serialized_end=341
  _globals['_GETSNAPVOTESRESPONSE']._serialized_start=343
  _globals['_GETSNAPVOTESRESPONSE']._serialized_end=409
  _globals['_VOTE']._serialized_start=411
  _globals['_VOTE']._serialized_end=521
  _globals['_VOTEREQUEST']._serialized_start=523
  _globals['_VOTEREQUEST']._serialized_end=593
  _globals['_USER']._serialized_start=596
  _globals['_USER']._serialized_end=1050
# @@protoc_insertion_point(module_scope)
