REVOKE ALL PRIVILEGES ON TABLE users FROM service;
REVOKE USAGE, SELECT ON SEQUENCE users_id_seq FROM service;
REVOKE ALL PRIVILEGES ON TABLE votes FROM service;
REVOKE USAGE, SELECT ON SEQUENCE votes_id_seq FROM service;
REVOKE CONNECT ON DATABASE ratings FROM service;

DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS users;

