REVOKE ALL PRIVILEGES ON TABLE users FROM CURRENT_USER;
REVOKE USAGE, SELECT ON SEQUENCE users_id_seq FROM CURRENT_USER;
REVOKE ALL PRIVILEGES ON TABLE votes FROM CURRENT_USER;
REVOKE USAGE, SELECT ON SEQUENCE votes_id_seq FROM CURRENT_USER;
REVOKE CONNECT ON DATABASE ratings FROM CURRENT_USER;

DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS users;

