name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build Ratings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0
          components: clippy, rustfmt

      - name: Install additional build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

          sudo snap install protobuf --classic

      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Lint code
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ratings
          path: target/release/ratings
